import pymusik as pm

# Pythonic Doom,
# A music example by Ericson Willians.

if __name__ == '__main__':

	music = pm.Music([
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G_SHARP)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.A_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.B)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.A_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.B)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G_SHARP)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.A_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.B)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.A_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.B)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G + 3)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G_SHARP + 3)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G + 3)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G_SHARP + 3)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.C_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.D)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.C_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.D)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G + 3)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G_SHARP + 3)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G + 3)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G_SHARP + 3)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.C_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.D)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.C_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.D)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G_SHARP)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.A_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.B)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.A_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.B)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G_SHARP)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G)),
	pm.Chord(pm.Note(3, pm.C, pm.MINIM), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.A_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.B)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.A_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP, pm.MINIM), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.F_SHARP), pm.Note(5, pm.B)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G + 3)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G_SHARP + 3)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G + 3)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G_SHARP + 3)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.C_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.D)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.C_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.D)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G + 3)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G_SHARP + 3)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G + 3)),
	pm.Chord(pm.Note(3, pm.C + 3, pm.MINIM), pm.Note(5, pm.C + 3), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.G_SHARP + 3)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.C_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.D)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.C_SHARP)),
	pm.Chord(pm.Note(3, pm.D_SHARP + 3, pm.MINIM), pm.Note(5, pm.D_SHARP + 3), pm.Note(5, pm.F_SHARP + 3), pm.Note(5, pm.D)),
	pm.Chord(pm.Note(3, pm.C, pm.WHOLE), pm.Note(5, pm.C), pm.Note(5, pm.D_SHARP), pm.Note(5, pm.G))]
	)
	
	p = pm.Player(pm.ACOUSTIC_GRANDPIANO, music)
	p.play()
